export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const TOGGLE_SELECTED_TYPE = 'TOGGLE_SELECTED_TYPE';
export const TOGGLE_SELECTED_CATEGORY = 'TOGGLE_SELECTED_CATEGORY';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const SET_SORTING = 'SET_SORTING';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const REMOVE_ALL_FILTERS = 'REMOVE_ALL_FILTERS';